version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: shazam-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: shazam-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
