services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shazam-frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    container_name: shazam-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  
